### ISSUE TITLE
HttpException: Failed to parse header value error

### ISSUE THREAD

**Issue by ayberkcal** [cfug/dio#1591]
### New Issue Checklist

- [x ] I have searched for a similar issue in the [project](https://github.com/flutterchina/dio/issues) and found none

### Issue Info

| Info                           | Value                                                 |      |
| ------------------------------ | ----------------------------------------------------- | ---- |
| Platform Name                  | flutter                          |      |
| Dio Version                    | ^4.0.4                                  |      |
| Repro rate                     | all the time (100%)   |      |

### Issue Description and Steps

I try to call rest api and I have faced "HttpException: Failed to parse header value" exception. Why does it happen?
Request Type: **Post**
Exception Detail:
```
DioError [DioErrorType.other]: HttpException: Failed to parse header value
Source stack:
#0      DioMixin.fetch (package:dio/src/dio_mixin.dart:488:35)
#1      DioMixin.request (package:dio/src/dio_mixin.dart:483:12)
#2      DioMixin.post (package:dio/src/dio_mixin.dart:97:12)
#3      RestClient.post (package:project/core/rest_client.dart:61:34)
<asynchronous suspension>
#4      RestService.login (package:project/services/rest_service.dart:25:20)
<asynchronous suspension>
#5      LoginViewModel.login (package:project/view_model/login_view_model.dart:30:29)
<asynchronous suspension>
```

Also I sniff network with Fiddler and "WWW-Authenticate: User not registered." header causes error. How handle this problem? Because I cannot change response of the Api.

https://prnt.sc/6f6AkEry0Mhy

**Comment by ayberkcal** [comment]
I have talked with API provider and they remove "WWW-Authenticate: User not registered." header from response. Everythink works fine. I think there is an issue about parsing and this may important because dio cannot give any opportunite to handle this exception.
