### ISSUE TITLE
Couldn't build project with cookie_manager on Flutter Web

### ISSUE THREAD

**Issue by YazeedAlKhalaf** [cfug/dio#1799]
### Package

cookie_manager

### Version

3.0.0

### Output of `flutter doctor -v`

```shell
[!] Flutter (Channel stable, 3.7.12, on macOS 13.0.1 22A400 darwin-arm64, locale en-SA)
    • Flutter version 3.7.12 on channel stable at /Users/yazeedalkhalaf/fvm/versions/3.7.12
    ! Warning: `flutter` on your path resolves to /Users/yazeedalkhalaf/fvm/versions/3.7.6/bin/flutter, which is not inside your current Flutter SDK checkout at /Users/yazeedalkhalaf/fvm/versions/3.7.12. Consider adding /Users/yazeedalkhalaf/fvm/versions/3.7.12/bin to the front of your path.
    ! Warning: `dart` on your path resolves to /Users/yazeedalkhalaf/fvm/versions/3.7.6/bin/dart, which is not inside your current Flutter SDK checkout at /Users/yazeedalkhalaf/fvm/versions/3.7.12. Consider adding /Users/yazeedalkhalaf/fvm/versions/3.7.12/bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 4d9e56e694 (10 days ago), 2023-04-17 21:47:46 -0400
    • Engine revision 1a65d409c7
    • Dart version 2.19.6
    • DevTools version 2.20.1
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/yazeedalkhalaf/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /Users/yazeedalkhalaf/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/213.7172.25.2113.9123335/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14C18
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Users/yazeedalkhalaf/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/212.5712.43.2112.8815526/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] Android Studio (version 2021.3)
    • Android Studio at /Users/yazeedalkhalaf/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/213.7172.25.2113.9123335/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] IntelliJ IDEA Ultimate Edition (version 2022.2.1)
    • IntelliJ at /Users/yazeedalkhalaf/Applications/JetBrains Toolbox/IntelliJ IDEA Ultimate.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] IntelliJ IDEA Ultimate Edition (version 2022.2.1)
    • IntelliJ at /Users/yazeedalkhalaf/Library/Application Support/JetBrains/Toolbox/apps/IDEA-U/ch-0/222.3739.54/IntelliJ IDEA.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.77.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.62.0

[✓] Connected device (5 available)
[REMOVED THE DEVICES, BUT 5 APPEAR HERE]

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.
```
```


### Dart Version

2.19.6

### Steps to Reproduce

1. make a new flutter project
2. add dependencies needed to use the plugin,  in `pubspec.yaml`
```yaml
dependencies:
  // other dependencies.

  dio: 
  dio_cookie_manager: 
  cookie_jar: 
```
4. run the project or build it.

This is a minimal code you could plug into your flutter project to reproduce the issue:
```dart
                final dio = Dio();
                if (!kIsWeb) {
                  final cookieJar = CookieJar();
                  dio.interceptors.add(CookieManager(cookieJar));
                }

                final response = await dio.get(
                  'https://jsonplaceholder.typicode.com/todos/1',
                );
                print(response);
```

### Expected Result

The project build and runs, but doesn't use the cookie implementation since it is on web.

### Actual Result

```
💪 Building with sound null safety 💪

Compiling lib/main.dart for the Web...                          
Target dart2js failed: Exception: Warning: The 'dart2js' entrypoint script is deprecated, please use 'dart compile js' instead.
../../../.pub-cache/hosted/pub.dev/dio_cookie_manager-3.0.0/lib/src/cookie_mgr.dart:58:12:
Error: Can't assign spread elements of type 'Cookie/*1*/' to collection elements of type 'Cookie/*2*/'.
 - 'Cookie/*1*/' is from 'package:cookie_jar/src/cookie/_cookie_web.dart' ('../../../.pub-cache/hosted/pub.dev/cookie_jar-4.0.1/lib/src/cookie/_cookie_web.dart').
 - 'Cookie/*2*/' is from 'dart:_http'.
        ...cookies,
           ^
../../../.pub-cache/hosted/pub.dev/dio_cookie_manager-3.0.0/lib/src/cookie_mgr.dart:122:56:
Error: The argument type 'List<Cookie/*1*/>' can't be assigned to the parameter type 'List<Cookie/*2*/>'.
 - 'List' is from 'dart:core'.
 - 'Cookie/*1*/' is from 'dart:_http'.
 - 'Cookie/*2*/' is from 'package:cookie_jar/src/cookie/_cookie_web.dart' ('../../../.pub-cache/hosted/pub.dev/cookie_jar-4.0.1/lib/src/cookie/_cookie_web.dart').
    await cookieJar.saveFromResponse(response.realUri, cookies);
                                                       ^
../../../.pub-cache/hosted/pub.dev/dio_cookie_manager-3.0.0/lib/src/cookie_mgr.dart:130:13:
Error: The argument type 'List<Cookie/*1*/>' can't be assigned to the parameter type 'List<Cookie/*2*/>'.
 - 'List' is from 'dart:core'.
 - 'Cookie/*1*/' is from 'dart:_http'.
 - 'Cookie/*2*/' is from 'package:cookie_jar/src/cookie/_cookie_web.dart' ('../../../.pub-cache/hosted/pub.dev/cookie_jar-4.0.1/lib/src/cookie/_cookie_web.dart').
            cookies,
            ^
Error: Compilation failed.

#0      Dart2JSTarget.build (package:flutter_tools/src/build_system/targets/web.dart:225:7)
<asynchronous suspension>
#1      _BuildInstance._invokeInternal (package:flutter_tools/src/build_system/build_system.dart:847:9)
<asynchronous suspension>
#2      Future.wait.<anonymous closure> (dart:async/future.dart:522:21)
<asynchronous suspension>
#3      _BuildInstance.invokeTarget (package:flutter_tools/src/build_system/build_system.dart:785:32)
<asynchronous suspension>
#4      Future.wait.<anonymous closure> (dart:async/future.dart:522:21)
<asynchronous suspension>
#5      _BuildInstance.invokeTarget (package:flutter_tools/src/build_system/build_system.dart:785:32)
<asynchronous suspension>
#6      FlutterBuildSystem.build (package:flutter_tools/src/build_system/build_system.dart:614:16)
<asynchronous suspension>
#7      buildWeb (package:flutter_tools/src/web/compile.dart:53:32)
<asynchronous suspension>
#8      BuildWebCommand.runCommand (package:flutter_tools/src/commands/build_web.dart:135:5)
<asynchronous suspension>
#9      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1257:27)
<asynchronous suspension>
#10     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#11     CommandRunner.runCommand (package:args/command_runner.dart:209:13)
<asynchronous suspension>
#12     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:283:9)
<asynchronous suspension>
#13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#14     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:229:5)
<asynchronous suspension>
#15     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:64:9)
<asynchronous suspension>
#16     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#17     main (package:flutter_tools/executable.dart:91:3)
<asynchronous suspension>

Compiling lib/main.dart for the Web...                              7.9s
Exception: Failed to compile application for the Web.
```

**Comment by AlexV525** [comment]
Closing because flutterchina/cookie_jar#37.
