### ISSUE TITLE
Fix error http error

### ISSUE THREAD

**Issue by starsoheil2007** [cfug/dio#1800]
### Package

dio

### Version

4.0.3

### Dart Version

2.14.4

### Steps to Reproduce

Hi to all
I want to send request to local server (http server);

I got this error :
`java.lang.ClassCastException: com.android.okhttp.internal.huc.HttpURLConnectionImpl cannot be cast to javax.net.ssl.HttpsURLConnection
`
I added this line to dio :

```
      var d = Dio()
        ..options.headers = {'Content-Type': 'application/json; charset=utf-8'};
      print('client_created');
      (d.httpClientAdapter as DefaultHttpClientAdapter).onHttpClientCreate =
          (HttpClient client) {
            print("dio xxxx");
            client.badCertificateCallback =
            (X509Certificate cert, String host, int port) => true;
        return client;
      };
      return d;
    }
```

### Expected Result

Get response

### Actual Result

this error :

```
E/AndroidRuntime(23933): java.lang.ClassCastException: com.android.okhttp.internal.huc.HttpURLConnectionImpl cannot be cast to javax.net.ssl.HttpsURLConnection
E/AndroidRuntime(23933): 	at diefferson.http_certificate_pinning.HttpCertificatePinningPlugin.getFingerprint(HttpCertificatePinningPlugin.kt:99)
E/AndroidRuntime(23933): 	at diefferson.http_certificate_pinning.HttpCertificatePinningPlugin.checkConnexion(HttpCertificatePinningPlugin.kt:91)
E/AndroidRuntime(23933): 	at diefferson.http_certificate_pinning.HttpCertificatePinningPlugin.handleCheckEvent(HttpCertificatePinningPlugin.kt:77)
E/AndroidRuntime(23933): 	at diefferson.http_certificate_pinning.HttpCertificatePinningPlugin.onMethodCall$lambda-0(HttpCertificatePinningPlugin.kt:56)
E/AndroidRuntime(23933): 	at diefferson.http_certificate_pinning.HttpCertificatePinningPlugin.lambda$tmYn8PAfUzdgAXWVDtDvHyTq2BQ(Unknown Source:0)
E/AndroidRuntime(23933): 	at diefferson.http_certificate_pinning.-$$Lambda$HttpCertificatePinningPlugin$tmYn8PAfUzdgAXWVDtDvHyTq2BQ.run(Unknown Source:6)
E/AndroidRuntime(23933): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
E/AndroidRuntime(23933): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
E/AndroidRuntime(23933): 	at java.lang.Thread.run(Thread.java:1012)
```

**Comment by AlexV525** [comment]
An older version (<5.0) is not in our supporting range.
