### ISSUE TITLE
RangeError when trying to run in Web Environment

### ISSUE THREAD

**Issue by coogle** [cfug/dio#1837]
### Package

dio

### Version

4.0.6

### Output of `flutter doctor -v`

```shell
[✓] Flutter (Channel stable, 3.10.2, on macOS 12.6.3 21G419 darwin-arm64, locale en-US)
    • Flutter version 3.10.2 on channel stable at /Users/john/Projects/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 9cd3d0d9ff (4 days ago), 2023-05-23 20:57:28 -0700
    • Engine revision 90fa3ae28f
    • Dart version 3.0.2
    • DevTools version 2.23.1

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/john/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 13F100
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 12.6.3 21G419 darwin-arm64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 113.0.5672.126

[✓] Network resources
    • All expected network resources are available.
```

### Dart Version

3.0.2

### Steps to Reproduce

I don't have specific steps to reproduce, beyond what I can say below..

I have this code to build my DIO object:

```
Client.defaultClient({
    CookieJar? cookieJar,
    String? csrfPath,
    bool log = false,
    String? baseUrl,
  })  : _cookieJar = cookieJar ?? CookieJar(),
        _csrfPath = csrfPath ?? "/api/csrf-cookie" {
    
    _dio = Dio();
    _dio.options.baseUrl = baseUrl ?? "http://localhost";
    _dio.options.responseType = ResponseType.plain;
    _dio.options.extra = {"withCredentials": true};
```

I later use this client as follows:

```
_dio.get(endpoint, queryParameters: queryParams)
```

One of the requests I need to make in my application is to the `/api/csrf-cookie` endpoint, which returns an empty body but sets some cookies for CSRF protection, etc. I need... 

### Expected Result

The API call works in production as it does in `localhost`

### Actual Result

In local development when using `http://localhost/` as the base Url everything works fine. When I move the flutter app to a production environment (public internet, SSL) I get the following error:

```
DioError [DioErrorType.other]: RangeError (end): Invalid value: Only valid value is 0: -1
RangeError (end): Invalid value: Only valid value is 0: -1
    at Object.wrapException (https://app.arvee.io/main.dart.js:9572:17)
    at Object.RangeError_checkValidRange (https://app.arvee.io/main.dart.js:14885:19)
    at Interceptor.substring$2 (https://app.arvee.io/main.dart.js:88775:42)
    at InjectWebCookiesInterceptor_onResponse_closure.call$1 (https://app.arvee.io/main.dart.js:114700:57)
    at JavaScriptObject.forEach$1 (https://app.arvee.io/main.dart.js:88097:11)
    at InjectWebCookiesInterceptor.onResponse$2 (https://app.arvee.io/main.dart.js:114689:27)
    at tear_off.<anonymous> (https://app.arvee.io/main.dart.js:9891:45)
    at DioMixin_fetch__responseInterceptorWrapper___closure.call$0 (https://app.arvee.io/main.dart.js:119332:24)
    at Object.DioMixin_checkIfNeedEnqueue (https://app.arvee.io/main.dart.js:22842:25)
    at DioMixin_fetch__responseInterceptorWrapper__closure.call$0 (https://app.arvee.io/main.dart.js:119325:16)
Source stack:
Error
    at Object.StackTrace_current (https://app.arvee.io/main.dart.js:14740:40)
    at https://app.arvee.io/main.dart.js:119007:30
    at _wrapJsFunctionForAsync_closure.$protected (https://app.arvee.io/main.dart.js:12392:15)
    at _wrapJsFunctionForAsync_closure.call$2 (https://app.arvee.io/main.dart.js:91508:12)
    at Object._asyncStartSync (https://app.arvee.io/main.dart.js:12356:20)
    at DioForBrowser.fetch$body$DioMixin (https://app.arvee.io/main.dart.js:119036:16)
    at DioForBrowser.fetch$1$1 (https://app.arvee.io/main.dart.js:118992:19)
    at https://app.arvee.io/main.dart.js:118980:48
    at _wrapJsFunctionForAsync_closure.$protected (https://app.arvee.io/main.dart.js:12392:15)
    at _wrapJsFunctionForAsync_closure.call$2 (https://app.arvee.io/main.dart.js:91508:12)
```

Looking in the code from the backtrace, it seems like it's dying trying to process the cookies:

```
InjectWebCookiesInterceptor_onResponse_closure.call
```

**Comment by coogle** [comment]
Note, that if I make a local build (flutter run -d chrome --web-port=50000) and set my endpoint to the deployed API endpoints instead of my `localhost` ones, it doesn't reproduce the error.

**Comment by AlexV525** [comment]
- 4.x versions are currently out of our support.
- CookieJar should not be used under the Web environment.

From your logs we cannot predicate what is happening because the stack trace points to project instead of our libraries.

**Comment by coogle** [comment]
@AlexV525 

You can't use CookieJar for web development? I must not understand something -- what do I need in order to support cookies? 

My use case is that I need to prior to any `POST` request against an endpoint API, first execute a `GET` request to `api/csrf-cookie` which sets a HTTP cookie in the client with a CSRF token as a security measure.

**Comment by kuhnroyal** [comment]
You probably need to set `BaseOptions(extra: {"withCredentials": true}))`, this should automatically attach all cookies to secure requests.
