### ISSUE TITLE
[BUG] [dio_http2_adapter] WRONG_VERSION_NUMBER tls_record.cc:231

### ISSUE THREAD

**Issue by zs-dima** [cfug/dio#1983]
### Package

http2_adapter

### Version

2.3.1+1

### Operating-System

Windows

### Output of `flutter doctor -v`

```shell
[√] Flutter (Channel stable, 3.13.5, on Microsoft Windows [Version 10.0.22621.2283], locale en-US)
    • Flutter version 3.13.5 on channel stable at c:\dev\flutter\stable
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 12fccda598 (8 days ago), 2023-09-19 13:56:11 -0700
    • Engine revision bd986c5ed2
    • Dart version 3.1.2
    • DevTools version 2.25.0

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.7.4)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.7.34031.279
    • Windows 10 SDK version 10.0.22621.0

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.22621.2283]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 117.0.5938.92
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 117.0.2045.36

[√] Network resources
    • All expected network resources are available.
```

### Dart Version

3.1.2

### Steps to Reproduce

Client works well without Http2Adapter on Windows and Web, but fails on Windows with Http2Adapter 

```dart
    _dio = Dio()
      ..options.baseUrl = '${host.url}/api/Files'
      ..interceptors.add(LogInterceptor())
      ..interceptors.add(
        InterceptorsWrapper(
          onRequest: (options, handler) async {
            final token = await getToken();
            options.headers['Authorization'] = 'Bearer $token';
            handler.next(options);
          },
        ),
      );

    _dio.httpClientAdapter = Http2Adapter(
      ConnectionManager(
        idleTimeout: const Duration(seconds: 15),
        onClientCreate: (_, config) => config.onBadCertificate = (_) => true,
      ),
    );

    final multipartFile = MultipartFile.fromStream(
      () => file.fileStream,
      file.fileSize,
      filename: file.fileName,
    );

    final response = await _dio.post<ResponseBody>(
      '/upload_file',
      data: FormData.fromMap({
        'file': multipartFile,
      }),
      cancelToken: cancelToken,
      options: Options(responseType: ResponseType.stream),
    );
```

.Net Core service endpoints
```json
"Kestrel": {
  "Endpoints": {
    "gRPC": {
      "Protocols": "Http2",
      "Url": "http://+:7000"
    },
    "gRPC-test": {
      "Protocols": "Http1AndHttp2",
      "Url": "http://+:7001"
    }
  }
}
```

### Expected Result

It could be nice if client will work on Windows with Http2Adapter 
Client works well without Http2Adapter on Windows and Web (port 7001), but fails on Windows with Http2Adapter.
Http2Adapter throws exception: WRONG_VERSION_NUMBER tls_record.cc:231

### Actual Result

```
uri: http://localhost:7000/api/Files/upload_file
flutter: DioException [unknown]: null
Error: HandshakeException: Handshake error in client (OS Error:
	WRONG_VERSION_NUMBER(../../third_party/boringssl/src/ssl/tls_record.cc:231))
```

**Comment by AlexV525** [comment]
Assuming we don't know anything about the .NET, would you be able to reproduce this using the `http2` without `dio`? If so, it's not related to our package.

**Comment by zs-dima** [comment]
@AlexV525 thanks a lot for looking into, http2 working well without dio, specially with gRPC over http2.

**Comment by AlexV525** [comment]
Could you provide minimal examples with:
- Using dio and the http2 adapter
- Using http2 without dio
plus a mininal runnable backend?

**Comment by farrukhnajmi** [comment]
I am having the same issue on my physical Android phone when I run my flutter app . The app runs fine in Android emulator `Pixel_3a_API_34_extension_level_7_x86_64` in Android Studio. I think my issue has to do with my Android API version which is API 33.

My phone info follows:

Hardware: samsung SM-A326U (Galaxy A32)
Android Version: 13
API version: 33

The error below occurs during a HTTP call to a server that only supports http (not https) protocol.

```
I/flutter (31795): 
I/flutter (31795): ╔╣ DioError ║ DioExceptionType.unknown
I/flutter (31795): ║  null
I/flutter (31795): ╚══════════════════════════════════════════════════════════════════════════════════════════╝
E/flutter (31795): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: DioException [unknown]: null
E/flutter (31795): Error: HandshakeException: Handshake error in client (OS Error: 
E/flutter (31795): 	WRONG_VERSION_NUMBER(tls_record.cc:231))
E/flutter (31795): #0      DioMixin.fetch.<anonymous closure> (package:dio/src/dio_mixin.dart:507:7)
E/flutter (31795): #1      _RootZone.runUnary (dart:async/zone.dart:1661:54)
E/flutter (31795): #2      _FutureListener.handleError (dart:async/future_impl.dart:174:22)
E/flutter (31795): #3      Future._propagateToListeners.handleError (dart:async/future_impl.dart:852:47)
E/flutter (31795): #4      Future._propagateToListeners (dart:async/future_impl.dart:873:13)
E/flutter (31795): #5      Future._completeError (dart:async/future_impl.dart:649:5)
E/flutter (31795): #6      _SyncCompleter._completeError (dart:async/future_impl.dart:60:12)
E/flutter (31795): #7      _Completer.completeError (dart:async/future_impl.dart:26:5)
E/flutter (31795): #8      Future.any.onError (dart:async/future.dart:620:45)
E/flutter (31795): #9      _RootZone.runBinary (dart:async/zone.dart:1666:54)
E/flutter (31795): #10     _FutureListener.handleError (dart:async/future_impl.dart:171:22)
E/flutter (31795): #11     Future._propagateToListeners.handleError (dart:async/future_impl.dart:852:47)
E/flutter (31795): #12     Future._propagateToListeners (dart:async/future_impl.dart:873:13)
E/flutter (31795): #13     Future._completeError (dart:async/future_impl.dart:649:5)
E/flutter (31795): #14     Future._asyncCompleteError.<anonymous closure> (dart:async/future_impl.dart:739:7)
E/flutter (31795): #15     _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
E/flutter (31795): #16     _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)
```

Please consider reopening this ticket.

**Comment by AlexV525** [comment]
@farrukhnajmi Please attach a minimal reproducible example.

**Comment by farrukhnajmi** [comment]
@AlexV525 I cannot seem to replicate it on a API 33 device such as a Pixel 7. So far I can only reproduce it on my physical phone Samsung Galaxy A32. So it is not API 33 specific. I think it may be a ca certificate issue on my physical phone. I just do not know. Others have reported the issue as you can see on a web search. 

I am using:
retrofit: ^4.0.3
retrofit_generator: ^8.0.4
dio: ^5.3.4

All close to latest versions. Sorry I have been unable to provide a reproducible version.

**Comment by AlexV525** [comment]
I think I've found a way to statically reproduce this by requesting https://flutter.cn/nkjnjknjn.html.
@farrukhnajmi @zs-dima Can you guys verify it?

**Comment by AlexV525** [comment]
The exception indicates that the current destination is not backed by a TLS connection, typically HTTP requests. But we use `SecureSocket` all the time regardless the scheme which mismatches the security condition.
