### ISSUE TITLE
An error occurred when using compute and download together

### ISSUE THREAD

**Issue by hgraceb** [cfug/dio#2018]
### Package

dio

### Version

5.3.3

### Operating-System

Windows

### Output of `flutter doctor -v`

```shell
[√] Flutter (Channel stable, 3.7.8, on Microsoft Windows [版本 10.0.19045.3448], locale zh-CN)
    • Flutter version 3.7.8 on channel stable at D:\Backup\Environment\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 90c64ed42b (8 months ago), 2023-03-21 11:27:08 -0500
    • Engine revision 9aa7816315
    • Dart version 2.19.5
    • DevTools version 2.20.1

[X] Windows Version (Unable to confirm if installed Windows version is 10 or greater)

[√] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at C:\Users\Flop\AppData\Local\Android\sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at:
      C:\Users\Flop\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\222.4459.24.2221.9862592\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-9586694)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.11.18)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.11.32802.440
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 2021.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[√] Android Studio (version 2022.2)
    • Android Studio at C:\Users\Flop\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\222.4459.24.2221.9862592
    • Flutter plugin version 73.0.2
    • Dart plugin version 222.4560
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-9586694)

[√] VS Code, 64-bit edition (version 1.76.2)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension can be installed from:
       https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [版本 10.0.19045.3448]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 118.0.5993.89
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 116.0.1938.69

[√] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.
```

### Dart Version

2.19.5

### Steps to Reproduce

```dart
import 'package:dio/dio.dart';
import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';

void main() => runApp(_MyApp());

class _MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) => MaterialApp(home: _MyHomePage());
}

class _MyHomePage extends StatefulWidget {
  @override
  State<_MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<_MyHomePage> {
  @override
  void initState() {
    super.initState();
    () async {
      final requester = _IsolateRequester(_HttpRequester());
      await requester.dio.download(await requester.request(), 'D:/test.data');
      await requester.dio.download(await requester.request(), 'D:/test.data');
    }();
  }

  @override
  Widget build(BuildContext context) => const SizedBox.shrink();
}

class _HttpRequester {
  final client = Dio(BaseOptions(
    // persistentConnection: false,
    baseUrl: 'http://127.0.0.1:8080',
  ));

  Future<String> request() async {
    await client.get('');
    return client.options.baseUrl;
  }
}

class _IsolateRequester {
  _IsolateRequester(this._requester);

  final _HttpRequester _requester;

  Dio get dio => _requester.client;

  Future<String> request() async => compute((_) => _requester.request(), null);
}

```

### Expected Result

I'm not sure if this is an issue with Dio itself or with Dart, but everything works fine when `persistentConnection` is set to false.

### Actual Result

```
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Invalid argument(s): Illegal argument in isolate message: (object extends NativeWrapper - Library:'dart:io' Class: _NativeSocket@13069316)
#0      Isolate._spawnFunction (dart:isolate-patch/isolate_patch.dart:399:25)
#1      Isolate.spawn (dart:isolate-patch/isolate_patch.dart:379:7)
#2      Isolate.run (dart:isolate:238:15)
#3      compute (package:flutter/src/foundation/_isolates_io.dart:17:18)
#4      _IsolateRequester.request (package:example/main.dart:51:44)
#5      _MyHomePageState.initState.<anonymous closure> (package:example/main.dart:24:52)
<asynchronous suspension>
```

**Comment by kuhnroyal** [comment]
You need to create the Dio client inside the isolate.
Please read the `compute` documentation and read about isolates in general.

**Comment by hgraceb** [comment]
Thanks! Even though I've reviewed the basic documentation, I'm still unable to pinpoint the cause of the issue.

However, after running the program again with Flutter version 3.16.0-22.0.pre.3, I can now confirm from the new error stack trace that it is indeed a limitation of [SendPort.send()](https://api.flutter.dev/flutter/dart-isolate/SendPort/send.html) itself:

> If the sender and receiver isolate share the same code (e.g. isolates created via [Isolate.spawn](https://api.flutter.dev/flutter/dart-isolate/Isolate/spawn.html)), the transitive object graph of message can contain any object, with the following exceptions:
> 
> - Objects with native resources (subclasses of e.g. NativeFieldWrapperClass1). A [Socket](https://api.flutter.dev/flutter/dart-io/Socket-class.html) object for example refers internally to objects that have native resources attached and can therefore not be sent.

```
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Invalid argument(s): Illegal argument in isolate message: object is unsendable - Library:'dart:async' Class: _Future@4048458 (see restrictions listed at `SendPort.send()` documentation for more information)
 <- _streamFuture in Instance of '_HttpClientConnection' (from dart:_http)
 <- hashCode in Instance of '_HashSetEntry<_HttpClientConnection>' (from dart:collection)
 <- _List len:8 (from dart:core)
 <- _buckets in Instance of '_HashSet<_HttpClientConnection>' (from dart:collection)
 <- _idle in Instance of '_ConnectionTarget' (from dart:_http)
 <- hashCode in Instance of '_HashMapEntry<String, _ConnectionTarget>' (from dart:collection)
 <- _List len:8 (from dart:core)
 <- _buckets in Instance of '_HashMap<String, _ConnectionTarget>' (from dart:collection)
 <- _connectionTargets in Instance of '_HttpClient' (from dart:_http)
 <- _cachedHttpClient in Instance of 'IOHttpClientAdapter' (from package:dio/src/adapters/io_adapter.dart)
 <- Instance of 'DioForNative' (from package:dio/src/dio/dio_for_native.dart)
 <- client in Instance of '_HttpRequester' (from package:example/main.dart)
 <- _requester in Instance of '_IsolateRequester' (from package:example/main.dart)
 <- field this in _IsolateRequester.request.<anonymous closure> (from package:example/main.dart)
 <- field callback in compute.<anonymous closure> (from package:flutter/src/foundation/_isolates_io.dart)
 <- resultPort in Instance of '_RemoteRunner<String>' (from dart:isolate)

#0      Isolate._spawnFunction (dart:isolate-patch/isolate_patch.dart:398:25)
#1      Isolate.spawn (dart:isolate-patch/isolate_patch.dart:378:7)
#2      Isolate.run (dart:isolate:285:15)
#3      compute (package:flutter/src/foundation/_isolates_io.dart:18:18)
#4      compute (package:flutter/src/foundation/isolates.dart:76:19)
#5      _IsolateRequester.request (package:example/main.dart:56:37)
#6      _MyHomePageState.initState.<anonymous closure> (package:example/main.dart:26:52)
<asynchronous suspension>
```

For this reason, I wrote a test code:

```dart
Future<Socket> streamFuture = Socket.connect('localhost', 8080);
compute((_) => streamFuture, null);
```

And as expected, it resulted in a similar error:

```
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Invalid argument(s): Illegal argument in isolate message: object is unsendable - Library:'dart:async' Class: _Future@4048458 (see restrictions listed at `SendPort.send()` documentation for more information)
 <- field streamFuture in _MyHomePageState.initState.<anonymous closure> (from package:example/main.dart)
 <- field callback in compute.<anonymous closure> (from package:flutter/src/foundation/_isolates_io.dart)
 <- resultPort in Instance of '_RemoteRunner<Socket>' (from dart:isolate)

#0      Isolate._spawnFunction (dart:isolate-patch/isolate_patch.dart:398:25)
#1      Isolate.spawn (dart:isolate-patch/isolate_patch.dart:378:7)
#2      Isolate.run (dart:isolate:285:15)
#3      compute (package:flutter/src/foundation/_isolates_io.dart:18:18)
#4      compute (package:flutter/src/foundation/isolates.dart:76:19)
#5      _MyHomePageState.initState (package:example/main.dart:30:5)
```

**Comment by kuhnroyal** [comment]
In simple terms, you can not construct the Dio client "outside "of the isolate and expect it to work "inside".
Isolates don't share any state, you can only pass messages.

So you can pass the URL to the compute function and have it return a result, but everything else has to happen in the isolate.
Best practice is to use a global function as argument for compute. This way it is harder to depend on state that is not actually available.
