### ISSUE TITLE
Error: Exception in Java code called through JNI: java.lang.RuntimeException: All available Cronet providers are disabled. A provider should be enabled before it can be used.

### ISSUE THREAD

**Issue by 2673542667** [cfug/dio#2116]
### Package

native_dio_adapter

### Version

1.3.0

### Operating-System

Android

### Output of `flutter doctor -v`

```shell
[!] Flutter (Channel stable, 3.16.5, on macOS 14.3.1 23D60 darwin-arm64, locale
    zh-Hans-CN)
    • Flutter version 3.16.5 on channel stable at
      /Users/huangyulin/fvm/versions/3.16.5
    ! Warning: `dart` on your path resolves to
      /opt/homebrew/Cellar/dart/3.0.5/libexec/bin/dart, which is not inside your
      current Flutter SDK checkout at /Users/huangyulin/fvm/versions/3.16.5.
      Consider adding /Users/huangyulin/fvm/versions/3.16.5/bin to the front of
      your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 78666c8dc5 (9 weeks ago), 2023-12-19 16:14:14 -0800
    • Engine revision 3f3e560236
    • Dart version 3.2.3
    • DevTools version 2.28.4
    • If those were intentional, you can disregard the above warnings; however
      it is recommended to use "git" directly to perform update checks and
      upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/huangyulin/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      17.0.7+0-17.0.7b1000.6-10550314)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15C500b
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2023.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      17.0.7+0-17.0.7b1000.6-10550314)

[!] Proxy Configuration
    • HTTP_PROXY is set
    ! NO_PROXY is not set

[✓] Connected device (5 available)
    • CET AL00 (mobile)          • 4EV0222920018398                     •
      android-arm64  • Android 12 (API 31)
    • 快乐的鸡翅 (mobile)             • 00008120-00125C94366BC01E            • ios
      • iOS 17.2.1 21C66
    • iPhone 15 Pro Max (mobile) • 2D6C4F08-4A61-4A07-9B48-84E81465AC06 • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-17-2 (simulator)
    • macOS (desktop)            • macos                                •
      darwin-arm64   • macOS 14.3.1 23D60 darwin-arm64
    • Chrome (web)               • chrome                               •
      web-javascript • Google Chrome 121.0.6167.184
    ! Error: Browsing on the local area network for 舒小舒舒的iPhone. Ensure the
      device is unlocked and attached with a cable or associated with the same
      local area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code
      -27)

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 2 categories.
```

### Dart Version

3.2.3

### Steps to Reproduce

Enter the App and request the network interface

### Expected Result

The request is successful and data is returned

### Actual Result

I/flutter ( 8846): Error: Exception in Java code called through JNI: java.lang.RuntimeException: All available Cronet providers are disabled. A provider should be enabled before it can be used.
I/flutter ( 8846): 
I/flutter ( 8846): java.lang.RuntimeException: All available Cronet providers are disabled. A provider should be enabled before it can be used.
I/flutter ( 8846): 	at org.chromium.net.CronetEngine$Builder.getEnabledCronetProviders(CronetEngine.java:365)
I/flutter ( 8846): 	at org.chromium.net.CronetEngine$Builder.createBuilderDelegate(CronetEngine.java:327)
I/flutter ( 8846): 	at org.chromium.net.CronetEngine$Builder.<init>(CronetEngine.java:75)
I/flutter ( 8846): 
E/flutter ( 8846): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: DioException [unknown]: null

**Comment by AlexV525** [comment]
This may mean your device doesn't have GMS support. Wait until https://github.com/dart-lang/http/pull/1111 lands and switch to an embedded implementation. There is nothing the adapter can do at this point.

**Comment by kuhnroyal** [comment]
> > This may mean your device doesn't have GMS support. Wait until [dart-lang/http#1111](https://github.com/dart-lang/http/pull/1111) lands and switch to an embedded implementation. There is nothing the adapter can do at this point.
> 
> How to switch to an embedded implementation?

https://pub.dev/packages/cronet_http#use-embedded-cronet
