### ISSUE TITLE
'package:dio/src/options.dart': Failed assertion: line 102 pos 12: 'value.isEmpty || kIsWeb || Uri.parse(value).host.isNotEmpty': is not true.

### ISSUE THREAD

**Issue by wm-jenildgohel** [cfug/dio#2126]
### Package

dio

### Version

5.4.1

### Operating-System

Android

### Output of `flutter doctor -v`

```shell
(base) wmt-jenilg@wmtjenilg:~$ flutter doctor -v
[✓] Flutter (Channel stable, 3.19.0, on Ubuntu 22.04.4 LTS 6.5.0-21-generic,
    locale en_IN)
    • Flutter version 3.19.0 on channel stable at
      /mnt/WMT_Mobile/Software/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision bae5e49bc2 (3 weeks ago), 2024-02-13 17:46:18 -0800
    • Engine revision 04817c99c9
    • Dart version 3.3.0
    • DevTools version 2.31.1

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /mnt/WMT_Mobile/Software/Android/Sdk
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = /mnt/WMT_Mobile/Software/Android/Sdk
    • ANDROID_SDK_ROOT = /mnt/WMT_Mobile/Software/Android/Sdk
    • Java binary at: /mnt/WMT_Mobile/Software/android-studio/jbr/bin/java
    • Java version OpenJDK Runtime Environment (build
      17.0.9+0-17.0.9b1087.7-11185874)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✗] Linux toolchain - develop for Linux desktop
    ✗ clang++ is required for Linux development.
      It is likely available from your distribution (e.g.: apt install clang),
      or can be downloaded from https://releases.llvm.org/
    ✗ CMake is required for Linux development.
      It is likely available from your distribution (e.g.: apt install cmake),
      or can be downloaded from https://cmake.org/download/
    ✗ ninja is required for Linux development.
      It is likely available from your distribution (e.g.: apt install
      ninja-build), or can be downloaded from
      https://github.com/ninja-build/ninja/releases
    ✗ pkg-config is required for Linux development.
      It is likely available from your distribution (e.g.: apt install
      pkg-config), or can be downloaded from
      https://www.freedesktop.org/wiki/Software/pkg-config/

[✓] Android Studio (version 2023.2)
    • Android Studio at /mnt/WMT_Mobile/Software/android-studio
    • Flutter plugin version 78.0.2
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • android-studio-dir = /mnt/WMT_Mobile/Software/android-studio
    • Java version OpenJDK Runtime Environment (build
      17.0.9+0-17.0.9b1087.7-11185874)

[✓] VS Code (version 1.87.0)
    • VS Code at /usr/share/code
    • Flutter extension version 3.84.0

[✓] Connected device (3 available)
    • CPH2467 (mobile) • bccf5979 • android-arm64  • Android 13 (API 33)
    • Linux (desktop)  • linux    • linux-x64      • Ubuntu 22.04.4 LTS
      6.5.0-21-generic
    • Chrome (web)     • chrome   • web-javascript • Google Chrome 122.0.6261.94

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
```

### Steps to Reproduce

i have base url configuration like this :

```dart
class ApiConst {}

class BaseUrl {
  //Local
  // static const DOMAIN = "";
  // static const COMMON_DOMAIN = "";
  //DEv
  // static const COMMON_DOMAIN = "";
  // static const DOMAIN = "";
  //Prod
  static const COMMON_DOMAIN = "";
  static const DOMAIN = "www.google.com";

  static const API = DOMAIN + "/api/v1";
  static const STORAGE = DOMAIN + "/storage/";

  static getBaseUrl() {
    return API;
  }
}
```

: which I am using over here : import 'dart:async';

```dart
import 'dart:convert';
import 'package:dio/dio.dart';
import 'package:flutter/foundation.dart';
import 'package:pretty_dio_logger/pretty_dio_logger.dart';
import 'package:shared_preferences/shared_preferences.dart';
import 'package:demo_test/redux/app_store.dart';
import 'package:demo_test/redux/actions/store_action.dart';
import 'package:demo_test/utils/api_const.dart';
import 'package:demo_test/utils/common_utils.dart';

class ApiBaseHelper {
  final Dio _dio = Dio();

  ApiBaseHelper({String? baseUrl}) {
    const Duration timeout = Duration(minutes: 3);
    _dio.options.baseUrl = baseUrl ?? BaseUrl.API;
    _dio.options.connectTimeout = timeout;
    _dio.options.receiveTimeout = timeout;
    if (kDebugMode) {
      _dio.interceptors.add(
        PrettyDioLogger(
          requestHeader: true,
          requestBody: true,
          /// As all are default value, so could be set directly.
          // responseHeader: false,
          // responseBody: true,
          // error: true,
          // maxWidth: 90,
          // compact: true,
          logPrint: appDebugPrint,
        ),
      );
    }
    _dio.interceptors.add(
      InterceptorsWrapper(
        onRequest: onRequest,
        onError: onError,
      ),
    );
  }

  Future<void> onRequest(RequestOptions options, RequestInterceptorHandler handler) async {
    final token = AppStore.store?.state.token;
    if (token != null && token != "") {
      options.headers['Authorization'] = 'Bearer $token';
    }

    return handler.next(options); // Continue.
  }

  Future<void> onError(DioException dioError,ErrorInterceptorHandler handler) async {


    final Response<dynamic>? response = dioError.response;
    if (response != null) {
      switch (response.statusCode) {
        case 401:
          CommonUtils.showMessage(
            response.data["meta"]["message"],
            type: MessageType.FAILED,
          );
          break;
        case 422:
          CommonUtils.showMessage(
            response.data["meta"]["message"],
            type: MessageType.FAILED,
          );
          break;
        case 503:
          AppStore.store?.dispatch(StoreAction(type: ActionType.Reset, data: null));
          CommonUtils.showMessage("Session expired", type: MessageType.FAILED);
          /*Navigate to login screen from here
          NavigationService.instance.resetToRoute(Routes.Login);*/
          break;
        default:
          CommonUtils.showMessage(
            "Something went wrong!",
            type: MessageType.FAILED,
          );
          break;
      }
    }

    return handler.next(dioError); // Continue.
  }

  void showNoInternet(e) {
    print("$e");
    if (e.message.toString().contains('SocketException')) {
      CommonUtils.showMessage(
        "No Internet Connection",
        type: MessageType.FAILED,
      );
    }
  }

  Future get(String url) async {
    dynamic responseJson;
    try {
      final response = await _dio.get(url);
      responseJson = _returnResponse(response);
    } catch (e) {
      showNoInternet(e);
    }

    return responseJson;
  }

  Future post(String url, {var body}) async {
    dynamic responseJson;
    try {
      Response response = await _dio.post(url, data: jsonEncode(body));
      responseJson = _returnResponse(response);
    } catch (e) {
      showNoInternet(e);
    }

    return responseJson;
  }

  Future postFormData(String url, {var body, onProgress}) async {
    dynamic responseJson;
    try {
      final Response response = await _dio.post(
        url,
        data: FormData.fromMap(body),
        onSendProgress: (sent, total) =>
        onProgress != null ? onProgress(sent / total) : null,
      );
      responseJson = _returnResponse(response);
    } catch (e) {
      showNoInternet(e);
    }

    return responseJson;
  }

  Future put(String url, var body) async {
    dynamic responseJson;
    try {
      final response = await _dio.put(url, data: body);
      responseJson = _returnResponse(response);
    } catch (e) {
      showNoInternet(e);
    }
    print(responseJson.toString());

    return responseJson;
  }

  Future delete(String url) async {
    dynamic apiResponse;
    try {
      final response = await _dio.delete(url);
      apiResponse = _returnResponse(response);
    } catch (e) {
      showNoInternet(e);
    }

    return apiResponse;
  }

  void appDebugPrint(Object message) {
    debugPrint(message.toString());
  }

  dynamic _returnResponse(Response response) {
    return response.data;
  }
}
```

: and in this on app start I am having the issue

### Expected Result

app should be running good

### Actual Result

```console
Launching lib/main.dart on CPH2467 in debug mode...
Running Gradle task 'assembleDebug'...
✓  Built build/app/outputs/flutter-apk/app-debug.apk.
Installing build/app/outputs/flutter-apk/app-debug.apk...
Debug service listening on ws://127.0.0.1:36751/Fo9RYpQsiRQ=/ws
Syncing files to device CPH2467...
W/ample.demo_test( 7345): Cleared Reference was only reachable from finalizer (only reported once)
D/OpenGLRenderer( 7345): SkiaOpenGLPipeline::setSurface: this=0xb400007ade735000, surface=NULL
I/RootBeer( 7345): LOOKING FOR BINARY: /data/local/su Absent :(
I/RootBeer( 7345): LOOKING FOR BINARY: /data/local/bin/su Absent :(
I/RootBeer( 7345): LOOKING FOR BINARY: /data/local/xbin/su Absent :(
I/RootBeer( 7345): LOOKING FOR BINARY: /sbin/su Absent :(
I/RootBeer( 7345): LOOKING FOR BINARY: /su/bin/su Absent :(
I/RootBeer( 7345): LOOKING FOR BINARY: /system/bin/su Absent :(
I/RootBeer( 7345): LOOKING FOR BINARY: /system/bin/.ext/su Absent :(
I/RootBeer( 7345): LOOKING FOR BINARY: /system/bin/failsafe/su Absent :(
I/RootBeer( 7345): LOOKING FOR BINARY: /system/sd/xbin/su Absent :(
I/RootBeer( 7345): LOOKING FOR BINARY: /system/usr/we-need-root/su Absent :(
I/RootBeer( 7345): LOOKING FOR BINARY: /system/xbin/su Absent :(
I/RootBeer( 7345): LOOKING FOR BINARY: /cache/su Absent :(
I/RootBeer( 7345): LOOKING FOR BINARY: /data/su Absent :(
I/RootBeer( 7345): LOOKING FOR BINARY: /dev/su Absent :(
I/RootBeer( 7345): LOOKING FOR BINARY: /product/bin/su Absent :(
I/RootBeer( 7345): LOOKING FOR BINARY: /apex/com.android.runtime/bin/su Absent :(
I/RootBeer( 7345): LOOKING FOR BINARY: /apex/com.android.art/bin/su Absent :(
I/RootBeer( 7345): LOOKING FOR BINARY: /system_ext/bin/su Absent :(
I/RootBeer( 7345): LOOKING FOR BINARY: /odm/bin/su Absent :(
I/RootBeer( 7345): LOOKING FOR BINARY: /vendor/bin/su Absent :(
I/RootBeer( 7345): LOOKING FOR BINARY: /vendor/xbin/su Absent :(
I/Quality ( 7345): Skipped: false 9 cost 100.354935 refreshRate 11127598 bit true processName com.example.demo_test
I/Quality ( 7345): Skipped: false 1 cost 12.173694 refreshRate 11127598 bit true processName com.example.demo_test
D/ScrollOptim [SceneManager]( 7345): updateCurrentActivity: mCurrentActivityName=null, isOptEnable=true, isAnimAheadEnable=true, isFrameInsertEnable=true, InsertNum=1, isEnabledForScrollChanged=false
E/flutter ( 7345): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(invalid_icon, The resource app_logo could not be found. Please make sure it has been added as a drawable resource to your Android head project., null, null)
E/flutter ( 7345): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:651:7)
E/flutter ( 7345): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:334:18)
E/flutter ( 7345): <asynchronous suspension>
E/flutter ( 7345): #2      AndroidFlutterLocalNotificationsPlugin.initialize (package:flutter_local_notifications/src/platform_flutter_local_notifications.dart:142:12)
E/flutter ( 7345): <asynchronous suspension>
E/flutter ( 7345): #3      NotificationHandler._initializeNotification (package:demo_test/utils/notification_handler.dart:76:5)
E/flutter ( 7345): <asynchronous suspension>
E/flutter ( 7345): 
D/VRI[MainActivity]( 7345):  debugCancelDraw  cancelDraw=false,count = 939,android.view.ViewRootImpl@b25501c
D/VRI[MainActivity]( 7345): registerCallbacksForSync syncBuffer=false
D/VRI[MainActivity]( 7345): Received frameCommittedCallback lastAttemptedDrawFrameNum=1 didProduceBuffer=true syncBuffer=false
W/Parcel  ( 7345): Expecting binder but got null!
D/VRI[MainActivity]( 7345): draw finished.

======== Exception caught by widgets library =======================================================
The following assertion was thrown building Builder:
'package:dio/src/options.dart': Failed assertion: line 102 pos 12: 'value.isEmpty || kIsWeb || Uri.parse(value).host.isNotEmpty': is not true.

The relevant error-causing widget was: 
  MaterialApp MaterialApp:file:///mnt/WMT_Mobile/Demos/flutter/demo_test/lib/main.dart:64:20
When the exception was thrown, this was the stack: 
#2      OptionsMixin.baseUrl= (package:dio/src/options.dart:102:12)
#3      new ApiBaseHelper (package:demo_test/networking/api_base_helper.dart:17:18)
#4      new LoginRepo (package:demo_test/screens/non_auth/login/repo/login_repo.dart:4:40)
#5      new LoginBloc (package:demo_test/screens/non_auth/login/bloc/login_bloc.dart:4:27)
#6      new _LoginState (package:demo_test/screens/non_auth/login/login.dart:17:27)
#7      Login.createState (package:demo_test/screens/non_auth/login/login.dart:12:12)
#8      new StatefulElement (package:flutter/src/widgets/framework.dart:5564:25)
#9      StatefulWidget.createElement (package:flutter/src/widgets/framework.dart:776:38)
...     Normal element mounting (220 frames)
#229    Element.inflateWidget (package:flutter/src/widgets/framework.dart:4335:16)
#230    MultiChildRenderObjectElement.inflateWidget (package:flutter/src/widgets/framework.dart:6893:36)
#231    Element.updateChild (package:flutter/src/widgets/framework.dart:3846:18)
#232    Element.updateChildren (package:flutter/src/widgets/framework.dart:4033:32)
#233    MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6918:17)
#234    Element.updateChild (package:flutter/src/widgets/framework.dart:3824:15)
#235    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505:16)
#236    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5643:11)
#237    Element.rebuild (package:flutter/src/widgets/framework.dart:5196:7)
#238    StatefulElement.update (package:flutter/src/widgets/framework.dart:5666:5)
#239    Element.updateChild (package:flutter/src/widgets/framework.dart:3824:15)
#240    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505:16)
#241    Element.rebuild (package:flutter/src/widgets/framework.dart:5196:7)
#242    ProxyElement.update (package:flutter/src/widgets/framework.dart:5809:5)
#243    Element.updateChild (package:flutter/src/widgets/framework.dart:3824:15)
#244    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505:16)
#245    Element.rebuild (package:flutter/src/widgets/framework.dart:5196:7)
#246    ProxyElement.update (package:flutter/src/widgets/framework.dart:5809:5)
#247    _InheritedNotifierElement.update (package:flutter/src/widgets/inherited_notifier.dart:105:11)
#248    Element.updateChild (package:flutter/src/widgets/framework.dart:3824:15)
#249    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505:16)
#250    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5643:11)
#251    Element.rebuild (package:flutter/src/widgets/framework.dart:5196:7)
#252    StatefulElement.update (package:flutter/src/widgets/framework.dart:5666:5)
#253    Element.updateChild (package:flutter/src/widgets/framework.dart:3824:15)
#254    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505:16)
#255    Element.rebuild (package:flutter/src/widgets/framework.dart:5196:7)
#256    ProxyElement.update (package:flutter/src/widgets/framework.dart:5809:5)
#257    _InheritedNotifierElement.update (package:flutter/src/widgets/inherited_notifier.dart:105:11)
#258    Element.updateChild (package:flutter/src/widgets/framework.dart:3824:15)
#259    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505:16)
#260    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5643:11)
#261    Element.rebuild (package:flutter/src/widgets/framework.dart:5196:7)
#262    StatefulElement.update (package:flutter/src/widgets/framework.dart:5666:5)
#263    Element.updateChild (package:flutter/src/widgets/framework.dart:3824:15)
#264    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505:16)
#265    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5643:11)
#266    Element.rebuild (package:flutter/src/widgets/framework.dart:5196:7)
#267    StatefulElement.update (package:flutter/src/widgets/framework.dart:5666:5)
#268    Element.updateChild (package:flutter/src/widgets/framework.dart:3824:15)
#269    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6765:14)
#270    Element.updateChild (package:flutter/src/widgets/framework.dart:3824:15)
#271    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6765:14)
#272    Element.updateChild (package:flutter/src/widgets/framework.dart:3824:15)
#273    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505:16)
#274    Element.rebuild (package:flutter/src/widgets/framework.dart:5196:7)
#275    ProxyElement.update (package:flutter/src/widgets/framework.dart:5809:5)
#276    Element.updateChild (package:flutter/src/widgets/framework.dart:3824:15)
#277    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505:16)
#278    Element.rebuild (package:flutter/src/widgets/framework.dart:5196:7)
#279    ProxyElement.update (package:flutter/src/widgets/framework.dart:5809:5)
#280    Element.updateChild (package:flutter/src/widgets/framework.dart:3824:15)
#281    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505:16)
#282    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5643:11)
#283    Element.rebuild (package:flutter/src/widgets/framework.dart:5196:7)
#284    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2904:19)
#285    WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:989:21)
#286    RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:448:5)
#287    SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1386:15)
#288    SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1311:9)
#289    SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:1169:5)
#290    _invoke (dart:ui/hooks.dart:312:13)
#291    PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:399:5)
#292    _drawFrame (dart:ui/hooks.dart:283:31)
(elided 2 frames from class _AssertionError)
====================================================================================================
D/CompatibilityChangeReporter( 7345): Compat change id reported: 78294732; UID 10803; state: ENABLED
D/ScrollOptim [SceneManager]( 7345): updateCurrentActivity: mCurrentActivityName=com.example.demo_test.MainActivity, isOptEnable=true, isAnimAheadEnable=true, isFrameInsertEnable=true, InsertNum=1, isEnabledForScrollChanged=false
D/VRI[MainActivity]( 7345): onFocusEvent true
D/VRI[MainActivity]( 7345): send msg MSG_WINDOW_FOCUS_CHANGED with caller android.view.ViewRootImplExtImpl.markAndDumpWindowFocusChangeMsg:1003 android.view.ViewRootImpl.windowFocusChanged:9827 android.view.ViewRootImpl$WindowInputEventReceiver.onFocusEvent:9540 android.os.MessageQueue.nativePollOnce:-2 android.os.MessageQueue.next:349 android.os.Looper.loopOnce:186 android.os.Looper.loop:351 android.app.ActivityThread.main:8423 java.lang.reflect.Method.invoke:-2 com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run:584 com.android.internal.os.ZygoteInit.main:1013 <bottom of call stack> <bottom of call stack> <bottom of call stack> <bottom of call stack> <bottom of call stack> <bottom of call stack> <bottom of call stack> <bottom of call stack> <bottom of call stack> 
D/VRI[MainActivity]( 7345): handleWindowFocusChanged mWindowFocusChanged true mUpcomingWindowFocus true mAdded true
D/OplusScrollToTopManager( 7345): com.example.demo_test/com.example.demo_test.MainActivity,This DecorView@47fd4f0[MainActivity] change focus to true
D/VRI[MainActivity]( 7345): handleWindowFocusChanged mWindowFocusChanged false mUpcomingWindowFocus true mAdded true
V/AutofillManager( 7345): requestHideFillUi(null): anchor = null
D/OplusSystemUINavigationGestureExtImpl( 7345): regionString = null
D/VRI[MainActivity]( 7345): handleWindowFocusChanged mWindowFocusChanged false mUpcomingWindowFocus true mAdded true
D/OplusInputMethodManagerInternal( 7345): get inputMethodManager extension: com.android.internal.view.IInputMethodManager$Stub$Proxy@3a08cac
D/VRI[MainActivity]( 7345): handleWindowFocusChanged mWindowFocusChanged false mUpcomingWindowFocus true mAdded true
D/VRI[MainActivity]( 7345): handleWindowFocusChanged mWindowFocusChanged false mUpcomingWindowFocus true mAdded true
D/VRI[MainActivity]( 7345): handleWindowFocusChanged mWindowFocusChanged false mUpcomingWindowFocus true mAdded true
D/Activity( 7345): dispatchKeyEvent to com.example.demo_test.MainActivity@c9b5a4e will call onBackPressed
D/ScrollOptim [SceneManager]( 7345): updateCurrentActivity: mCurrentActivityName=null, isOptEnable=true, isAnimAheadEnable=true, isFrameInsertEnable=true, InsertNum=1, isEnabledForScrollChanged=false
D/VRI[MainActivity]( 7345): onFocusEvent false
D/VRI[MainActivity]( 7345): send msg MSG_WINDOW_FOCUS_CHANGED with caller android.view.ViewRootImplExtImpl.markAndDumpWindowFocusChangeMsg:1003 android.view.ViewRootImpl.windowFocusChanged:9827 android.view.ViewRootImpl$WindowInputEventReceiver.onFocusEvent:9540 android.os.MessageQueue.nativePollOnce:-2 android.os.MessageQueue.next:349 android.os.Looper.loopOnce:186 android.os.Looper.loop:351 android.app.ActivityThread.main:8423 java.lang.reflect.Method.invoke:-2 com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run:584 com.android.internal.os.ZygoteInit.main:1013 <bottom of call stack> <bottom of call stack> <bottom of call stack> <bottom of call stack> <bottom of call stack> <bottom of call stack> <bottom of call stack> <bottom of call stack> <bottom of call stack> 
D/VRI[MainActivity]( 7345): handleWindowFocusChanged mWindowFocusChanged true mUpcomingWindowFocus false mAdded true
D/VRI[MainActivity]( 7345): dispatchAppVisibility visible:false
I/SurfaceView( 7345): 202968339 surfaceDestroyed
D/BufferQueueProducer( 7345): [SurfaceView[com.example.demo_test/com.example.demo_test.MainActivity]#1(BLAST Consumer)1](id:1cb100000001,api:1,p:7345,c:7345) disconnect: api 1
D/BufferQueueProducer( 7345): [SurfaceView[com.example.demo_test/com.example.demo_test.MainActivity]#1(BLAST Consumer)1](id:1cb100000001,api:0,p:-1,c:7345) disconnect: api -1
D/BufferQueueConsumer( 7345): [SurfaceView[com.example.demo_test/com.example.demo_test.MainActivity]#1(BLAST Consumer)1](id:1cb100000001,api:0,p:-1,c:7345) disconnect
D/SurfaceView( 7345): 205317986positionLost mSurfaceControl is null return;
D/OpenGLRenderer( 7345): RenderProxy::destroy: this=0xb400007a5b290000, mContext=0xb400007a6df4d980
D/OpenGLRenderer( 7345): SkiaOpenGLPipeline::setSurface: this=0xb400007ade707000, surface=NULL
D/BufferQueueProducer( 7345): [VRI[MainActivity]#0(BLAST Consumer)0](id:1cb100000000,api:1,p:7345,c:7345) disconnect: api 1
D/BufferQueueConsumer( 7345): [VRI[MainActivity]#0(BLAST Consumer)0](id:1cb100000000,api:0,p:-1,c:7345) disconnect
D/VRI[MainActivity]( 7345): setWindowStopped stopped:true
D/OplusScrollToTopManager( 7345): com.example.demo_test/com.example.demo_test.MainActivity,window dying
D/OplusScrollToTopManager( 7345): com.example.demo_test/com.example.demo_test.MainActivity,unregisterSystemUIBroadcastReceiver 
D/OplusScrollToTopManager( 7345): com.example.demo_test/com.example.demo_test.MainActivity, unregisterSystemUIBroadcastReceiver failed java.lang.IllegalArgumentException: Receiver not registered: android.view.OplusScrollToTopManager$2@89726e0
D/OpenGLRenderer( 7345): RenderProxy::destroy: this=0xb400007a5b290000, mContext=0xb400007a6df4d980
D/OpenGLRenderer( 7345): SkiaOpenGLPipeline::setSurface: this=0xb400007ade707000, surface=NULL
```

**Comment by kuhnroyal** [comment]
You need to pass a full URL including scheme (`http://` or `https://`)
