### ISSUE TITLE
Issues with http2_adapter in dio causing HTTP/1.1 requests to fail and incorrect traffic type displayed in Flutter DevTools

### ISSUE THREAD

**Issue by TheWalkingDead1024** [cfug/dio#2341]
### Package

dio

### Version

5.7.0

### Operating-System

Android

### Adapter

Http2Adapter

### Output of `flutter doctor -v`

```shell
[✓] Flutter (Channel stable, 3.19.0, on macOS 14.5 23F79 darwin-arm64, locale zh-Hans-CN)
    • Flutter version 3.19.0 on channel stable at /Users/luhaobo/fvm/versions/3.19.0
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision bae5e49bc2 (10 months ago), 2024-02-13 17:46:18 -0800
    • Engine revision 04817c99c9
    • Dart version 3.3.0
    • DevTools version 2.31.1
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/luhaobo/Library/Android/sdk/
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = /Users/luhaobo/Library/Android/sdk/
    • Java binary at: /Users/luhaobo/Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.11+0-17.0.11b1207.24-11852314)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.4)
    • Xcode at /Applications/Xcode 15.4.app/Contents/Developer
    • Build 15F31d
    • CocoaPods version 1.16.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2024.1)
    • Android Studio at /Users/luhaobo/Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.11+0-17.0.11b1207.24-11852314)

[✓] VS Code (version 1.95.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.102.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 14.5 23F79 darwin-arm64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 131.0.6778.109
    ! Error: Browsing on the local area network for iPhone. Ensure the device is unlocked and attached with a cable or associated with the same local area
      network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)
    ! Error: Browsing on the local area network for iPhone. Ensure the device is unlocked and attached with a cable or associated with the same local area
      network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)
    ! Error: Browsing on the local area network for 鲁好波 iPhone 13 Pro (2700). Ensure the device is unlocked and attached with a cable or associated with
      the same local area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)
    ! Error: Browsing on the local area network for 鸣人的iPhone. Ensure the device is unlocked and attached with a cable or associated with the same local
      area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

### Dart Version

3.3.0

### Steps to Reproduce

1. Set up `dio` with `http2_adapter` as follows:
```
   final dio = Dio();
   dio.httpClientAdapter = Http2Adapter(
     ConnectionManager(
       idleTimeout: 10000,
     ),
   );
```
2.	Perform a HTTP/1.1 request using dio.
3.	Perform a HTTP/2 request using dio.
4.	Observe the traffic type in Flutter DevTools.

### Expected Result

HTTP/1.1 requests should be handled correctly without failing, and the network traffic should be appropriately categorized and displayed in Flutter DevTools.

### Actual Result

HTTP/1.1 requests fail when using http2_adapter, and the network traffic is incorrectly displayed as WebSocket traffic in Flutter DevTools.
![a0ed2302-0158-4692-bd16-30b1d2402aac](https://github.com/user-attachments/assets/c9d46d8f-bf56-420c-92d3-c10c58b3dc18)

**Comment by AlexV525** [comment]
Please provide a minimal reproducible example. We have a test to make sure that the adapter works with non-TLS requests and HTTP/1.x responses.

**Comment by SmartVive** [comment]
```
void main() async {
  final dio = Dio()
    ..options.baseUrl = 'http://pub.dev'
    ..interceptors.add(LogInterceptor())
    ..httpClientAdapter = Http2Adapter(
      ConnectionManager(idleTimeout: const Duration(seconds: 10)),
    );

  Response<String> response;
  response = await dio.get('/?xx=6');
  for (final e in response.redirects) {
    print('redirect: ${e.statusCode} ${e.location}');
  }
  print(response.data);
}
```

result:
```
*** Request ***
uri: http://pub.dev/?xx=6
method: GET
responseType: ResponseType.plain
followRedirects: true
persistentConnection: true
connectTimeout: null
sendTimeout: null
receiveTimeout: null
receiveDataWhenStatusError: true
extra: {}
headers:

Unhandled exception:
DioException [unknown]: null
Error: HTTP/2 error: Connection error: Connection is being forcefully terminated. (errorCode: 10)
#0      DioMixin.fetch (package:dio/src/dio_mixin.dart:520:7)
<asynchronous suspension>
#1      main (package:dio_example/http2_adapter.dart:13:14)
<asynchronous suspension>
*** DioException ***:
uri: http://pub.dev/?xx=6
DioException [unknown]: null
Error: HTTP/2 error: Connection error: Connection is being forcefully terminated. (errorCode: 10)
```

```
[√] Flutter (Channel stable, 3.24.5, on Microsoft Windows [Version 10.0.19045.5247], locale zh-CN)
    • Flutter version 3.24.5 on channel stable at C:\Users\Mountains\AppData\Local\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision dec2ee5c1f (6 weeks ago), 2024-11-13 11:13:06 -0800
    • Engine revision a18df97ca5
    • Dart version 3.5.4
    • DevTools version 2.37.3
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 35.0.0)
    • Android SDK at C:\Users\Mountains\AppData\Local\Android\sdk
    • Platform android-35, build-tools 35.0.0
    • Java binary at: C:\Program Files\Android\Android Studio1\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.10+0--11572160)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.10.1)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.10.34928.147
    • Windows 10 SDK version 10.0.22621.0

[√] Android Studio (version 2024.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 21.0.3+-12282718-b509.11)

[√] Android Studio (version 2024.1)
    • Android Studio at C:\Program Files\Android\Android Studio1
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • android-studio-dir = C:\Program Files\Android\Android Studio1
    • Java version OpenJDK Runtime Environment (build 17.0.10+0--11572160)

[√] Connected device (4 available)
    • IN2010 (mobile)   • 192.168.6.100:43219 • android-arm64  • Android 11 (API 30)
    • Windows (desktop) • windows             • windows-x64    • Microsoft Windows [Version 10.0.19045.5247]
    • Chrome (web)      • chrome              • web-javascript • Google Chrome 131.0.6778.205
    • Edge (web)        • edge                • web-javascript • Microsoft Edge 131.0.2903.112

[√] Network resources
    • All expected network resources are available.

• No issues found!

```

https://github.com/cfug/dio/blob/main/example_dart/lib/http2_adapter.dart
only modify `https://pub.dev` to `http://pub.dev`
http2_adapter can process http?
@AlexV525

**Comment by junko2013** [comment]
ConnectionManager(
          proxyConnectedPredicate: (protocol, status) {
            return status.contains('200') ||
                status.startsWith('HTTP/2.0') ||
                status.startsWith('HTTP/1.1 200');
          },
          idleTimeout: const Duration(seconds: 10),
        )  may it help

**Comment by SmartVive** [comment]
thx. But not working.&nbsp;I found the error is coming from here&nbsp;https://github.com/dart-lang/http/blob/dada989f4c30a618b6b707da23215802a8c6c085/pkgs/http2/lib/src/frames/frame_reader.dart#L79

I tried increasing maxFrameSize, but a new error occurred




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "cfug/dio"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年12月29日(星期天) 上午8:11
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [cfug/dio] Issues with http2_adapter in dio causing HTTP/1.1 requests to fail and incorrect traffic type displayed in Flutter DevTools (Issue #2341)





 
ConnectionManager(
 proxyConnectedPredicate: (protocol, status) {
 return status.contains('200') ||
 status.startsWith('HTTP/2.0') ||
 status.startsWith('HTTP/1.1 200');
 },
 idleTimeout: const Duration(seconds: 10),
 )  may it help

**Comment by AlexV525** [comment]
Related to https://github.com/dart-lang/http/issues/1383.
